services:
  db:
    image: mysql:8.0.33
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  back:
    platform: linux/x86_64
    build: .
    environment:
      RAILS_ENV: development
    volumes:
      - .:/rails
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  data-volume:

