services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: bin/rails s -b 0.0.0.0
    depends_on:
      - db
    volumes:
      - .:/myapp
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"

volumes:
  bundle_cache:
  pgdata:
