query background_getUnexecutedAction {
  getUnexecutedAction {
    id
    pattern
    executable {
        ... on Video {
          id
          url
        }
        ... on WatchList {
          id
          url
        }
    }
  }
}

mutation background_updateVideoEpisodeCountMutation(
  $input: UpdateVideoEpisodeCountMutationInput!
) {
  updateVideoEpisodeCount(input: $input) {
    action {
      id
      # NOTE: いる？
      executable {
        ... on Video {
            id
        }
      }
    }
  }
}

mutation background_createVideosMutation(
  $input: CreateVideosMutationInput!
) {
  createVideos(input: $input) {
    action {
      id
    }
  }
}