query background_getUnscrapedItem {
  getUnscrapedItem {
    id
    url
    video {
      id
    }
  }
}

mutation background_updateScrapedData($input: UpdateScrapedDataMutationInput!) {
  updateScrapedData(input: $input) {
    scrape {
      id
    }
  }
}